package code

var MsgFlags = map[int]string{
	SUCCESS:                   "ok",
	ERROR:                     "Server Error",
	InvalidParams:             "Invalid Params",
	IdNotEmpty:                "ID Empty",
	ErrorTokenEmpty:           "Token Empty",
	ErrorTokenInvalid:         "Token Invalid",
	ErrorTokenExpire:          "Token Expire",
	ErrorUserNotExist:         "User Not Exist",
	ErrorUserExist:            "User Exist",
	UserLoginNotAllow:         "User Login Not Allow",
	ErrorEmailSend:            "Error: Email Send",
	ErrorVerifyCodeEmpty:      "Error: Verify Code Empty",
	ErrorVerifyCodeInvalid:    "Error: Verify Code Invalid",
	ErrorVerifyCodeExpire:     "Error: Verify Code Expire",
	ErrorVerifyCodeInterval:   "Error: Verify Code Interval",
	ErrorVerifyCodeLimited:    "Error: Verify Code Limited",
	DbDuplicateEntry:          "Duplicate entry",
	ErrorUserPwd:              "Error: User Password",
	ErrorMerchantNotExist:     "Error: Merchant Haven't submitted verify code yet",
	ErrorMerchantExist:        "Error: Merchant Already Exist",
	ErrorShopBusinessNotExist: "Error: Shop Business Haven't submit ",
	ErrorShopBusinessExist:    "Error: Shop Business Already Exist",
	ErrorSkuCodeExist:         "Error: sku-code Already Exist",
	ErrorSkuCodeNotExist:      "Error: sku-code Not Exist",
	ErrorShopIdNotExist:       "Error: Shop Id Not Exist",
	ErrorShopIdExist:          "Error: Shop Id Already Exist",
	ErrorInviteCodeNotExist:   "Error: Invite Code Not Exist",
	ErrorSkuAmountNotEnough:   "Error: Sku Amount Not Enough",
	UserBalanceNotEnough:      "Error: User Balance Not Enough",
	UserAccountStateLock:      "Error: User Account State Lock",
	UserAccountNotExist:       "Error: User Account Not Exist",
	MerchantAccountNotExist:   "Error: Merchant Account Not Exist",
	MerchantAccountStateLock:  "Error: Merchant Account State Lock",
	DecimalParseErr:           "Error: Decimal Parse Err",
	TransactionFailed:         "Error: Transaction Failed",
	TradePayExpire:            "Error: Trade Pay Expire",
	TxCodeNotExist:            "Error: Tx Code Not Exist",
	TradeOrderTxCodeEmpty:     "Error: Trade Order Code Not Exist",
	TradeOrderExist:           "Error: Trade Order Exist",
	TradePayRun:               "Error: Trade Pay Run",
	TradePaySuccess:           "Error: Trade Pay Success",
	LogisticsRecordExist:      "Error: Logistics Record Exist",
	LogisticsRecordNotExist:   "Error: Logistics Record Not Exist",
	UserSettingInfoExist:      "Error: User Setting Info Exist",
	UserSettingInfoNotExist:   "Error: User Setting Info Not Exist",
	UserDeliveryInfoNotExist:  "Error: User Delivery Info Not Exist",
	TradeOrderNotMatchUser:    "Error: Trade Order Not Match User",
	SkuPriceVersionNotExist:   "Error: Sku Price Version Not Exist",
	OrderStateInvalid:         "Error: Order State Invalid",
	OrderStateLock:            "Error: Order State Lock",
	OrderExpire:               "Error: Order Expire",
	OrderPayCompleted:         "Error: Order Pay Completed",
	UserAccountStateInvalid:   "Error: User Account State Invalid",
	CommentsTagExist:          "Error: Comments Tag Exist",
	CommentsTagNotExist:       "Error: Comments Tag Not Exist",
	UserOrderNotExist:         "Error: User Order Not Exist",
	OutTradeEmpty:             "Error: Out Trade Empty",
}

func GetMsg(code int) string {
	msg, ok := MsgFlags[code]
	if ok {
		return msg
	}
	return MsgFlags[ERROR]
}
